FROM python:3.9-alpine
WORKDIR /app
COPY sub/redfish-stress-test/requirements.txt /app/
COPY sub/redfish-stress-test/RedfishStressTest.py /app/
RUN apk update && \
    apk add --no-cache gcc musl-dev linux-headers && \
    pip install -r requirements.txt && \
    apk del gcc musl-dev linux-headers

RUN echo '#!/bin/sh' > run.sh && \
    echo 'python /app/RedfishStressTest.py --test_rf_walk \
-i https://${ENDPOINT} -u ${USER} -p ${PASSWD} \
--runtime 1 --walk_count 10' >> run.sh && \
    chmod +x run.sh
