FROM python:3.9-alpine

WORKDIR /app

COPY tool_requirements.txt /app/requirements.txt
COPY sub/hms-tools/validation/test_streaming_telemetry.py /app/

RUN apk update && \
    pip install --upgrade pip && \
    pip install -r requirements.txt

EXPOSE 45900

RUN echo '#!/bin/sh' > run.sh && \
    echo 'python /app/test_streaming_telemetry.py \
-i ${LISTENIP} -u ${USER} -p ${PASSWD} -r 45900 -b ${BMC}' >> run.sh && \
    chmod +x run.sh
