FROM python:3.9-alpine

WORKDIR /app

COPY tool_requirements.txt /app/requirements.txt
COPY sub/hms-tools/validation/test_power_capping.py /app/

RUN apk update && \
    pip install --upgrade pip && \
    pip install -r requirements.txt

RUN echo '#!/bin/sh' > run.sh && \
    echo 'python /app/test_power_capping.py \
-u ${USER} -p ${PASSWD} -b ${BMC}' >> run.sh && \
    chmod +x run.sh
